### ISSUE TITLE
'Contract' object has no attribute 'eventFilter'

### ISSUE THREAD

**Issue by dilukangelosl** [Babajikumaresan/MEV-Tools#1]
Whats the Web3 version you are using? getting so many web3 errors

better if you can put a requirement.txt

**Comment by Babajikumaresan** [comment]
Done. requirement.txt file added in the repo

**Comment by Babajikumaresan** [comment]
[requirements.txt](https://github.com/Babajikumaresan/MEV-Tools/files/11379502/requirements.txt)
